/************************************************************************
 * Copyright (c) Crater Dog Technologies(TM).  All Rights Reserved.     *
 ************************************************************************
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.        *
 *                                                                      *
 * This code is free software; you can redistribute it and/or modify it *
 * under the terms of The MIT License (MIT), as published by the Open   *
 * Source Initiative. (See http://opensource.org/licenses/MIT)          *
 ************************************************************************/
'use strict';
var codex = require('./EncodingUtilities');
var forge = require('node-forge');


/**
 * This function returns a binary string of the specified size containing
 * randomly generated bytes.
 *
 * @param {number} numberOfBytes The number of bytes in the desired binary string.
 * @return {string} The binary string containing random bytes.
 */
exports.generateRandomBytes = function(numberOfBytes) {
    var bytes = forge.random.getBytesSync(numberOfBytes);
    return bytes;
};


/**
 * This function returns a random integer in the range in the
 * range [-2,147,483,648..2,147,483,647].
 *
 * @return {number} The random integer.
 */
exports.generateRandomInteger = function() {
    var integer = codex.bytesToInteger(exports.generateRandomBytes(4));
    return integer;
};


/**
 * This function returns the result of a weighted coin toss. A probability of
 * zero will always return false and a probability of one will always return true.
 *
 * @param {number} probability The probability that the toss will return true [0.0..1.0].
 * @return {boolean} The result of the coin toss.
 */
exports.coinToss = function(probability) {
    var randomInteger = exports.generateRandomInteger() & 0x7FFFFFFF;  // in range [0..2,147,483,647]
    var toss = randomInteger / 2147483648;  // convert to range [0.0..1.0)
    return toss < probability;  // true: [0.0..probability) and false: [probability..1.0]
};
