#!/bin/bash

echo "Emptying the citations bucket..."
./scripts/empty-bucket craterdog-bali-citations-us-west-2

echo "Emptying the drafts bucket..."
./scripts/empty-bucket craterdog-bali-drafts-us-west-2

echo "Emptying the documents bucket..."
./scripts/empty-bucket craterdog-bali-documents-us-west-2

echo "Emptying the types bucket..."
./scripts/empty-bucket craterdog-bali-types-us-west-2

echo "Emptying the queues bucket..."
./scripts/empty-bucket craterdog-bali-queues-us-west-2

