#!/usr/local/bin/python3

import sys
import boto3

session = boto3.Session()
s3 = session.resource(service_name='s3')
try:
    bucket = s3.Bucket(sys.argv[1])
    bucket.object_versions.delete()
except: Exception

