#!/bin/bash

cd dist/

echo "Creating a zip file for distribution to AWS..."
chmod 666 BaliNebulaRepository.js
zip -r BaliNebulaRepository.zip BaliNebulaRepository.js
chmod 666 BaliNebulaRepository.zip


echo "Pushing the latest version of the package out to S3..."
aws --region us-east-1 s3api put-object \
    --bucket craterdog-bali-nebula-us-east-1 \
    --key lambdas/BaliNebulaRepository.zip \
    --body ./BaliNebulaRepository.zip

echo "Done."
